### PR TITLE
LRDOCS-2888 documentation for corejsphook

### PR DESCRIPTION
**Pull request by olafk**
Hi Cody,
here's my take on LRDOCS-2888 - as you can see: One of the comments in there is a wild guess...

### CODE REVIEW

**Comment by olafk** [comment]
Added LRDOCS-2834 to this PR

**Comment by codyhoag** [comment]
@olafk Thanks for taking the time to work on these. I'll try to address your comments soon

**Comment by codyhoag** [comment]
@olafk I've merged these contributions into a local branch and am working off them now. I'm going to close this, since they're more like suggestions than a formal submission. I'll piece together what I can and ask the SMEs for parts that I can't. Thanks!

**Comment by codyhoag** [comment]
Sent blade.corejsphook part for final review: gamerson#131

**Pull request closed without merging**
